- name: Installing CLI tools
  hosts: localhost
  roles:
    - cli
    - cli-awesome
    - gnome-shell-extensions

- name: Deploying configuration of my tools on the dev servers
  hosts: server-group

  roles:
    - cli
