- name: Install CLI advanced programs
  package:
    name: "{{ item }}"
    state: latest
  become: true
  with_items:
    - ffmpeg
    - kid3
    - kid3-cli
    - python3-pip

- pip:
    name: youtube-dl
    state: latest
  become: true
