- name: Install CLI base programs
  package:
    name: "{{ item }}"
    state: latest
  become: true
  with_items:
    - vim
    - git
    - tmux

# including .bash_aliases file if present
- lineinfile:
    dest: ~/.bashrc
    state: present
    line: "if [ -f ~/.bash_aliases ]; then . ~/.bash_aliases ; fi # Including .bash_aliases file if present"
# including .bash_aliases_env, to load specific aliases to this environment
- lineinfile:
    dest: ~/.bashrc
    state: present
    line: "if [ -f ~/.bash_aliases_env ]; then . ~/.bash_aliases_env ; fi # including .bash_aliases_env, to load specific aliases to this environment"

# Dotfiles
- name: Creating dev home directory
  file:
    path: ~/dev/
    state: directory
    mode: '0755'
- name: Dotfiles
  git:
    repo: https://github.com/3615Yeye/dotfiles.git
    dest: ~/dev/dotfiles/
- name: Synchronize dotfiles to home directory
  synchronize:
    src: ~/dev/dotfiles/
    dest: ~/
    rsync_opts:
      - "--exclude=.git"

# Vim Plugins
- name: Creating directories for Vim
  file: path={{ item }} state=directory
  with_items:
      - ~/.vim/autoload
      - ~/.vim/plugged
- name: Downloading Plug package manager for Vim
  get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: ~/.vim/autoload/plug.vim
- name: Installing Vim plugins
  command: 'vim +PlugInstall +qall'
